### PR TITLE
New report for the text editing short survey

### PR DESCRIPTION
**Pull request by captainbrosset**
This PR adds a new .md file that reports on the results of the text & editing short survey, and proposes a few interpretations of the data.

Best way to review this is to use the GitHub markdown preview of the branch version here: https://github.com/web-platform-dx/developer-research/blob/text-editing-survey-report/mdn-short-surveys/2024-12-05-text-edit/README.md

### CODE REVIEW

**Comment by captainbrosset** [comment]
@tayloregivens can you please review this PR?

**Comment by tayloregivens** [comment]
Minor comment would be labeling the x axis on the graphs "number of participants". The y axis is clear and may not need naming. Besides that, the analysis looks great!

**Comment by captainbrosset** [comment]
> Minor comment would be labeling the x axis on the graphs "number of participants". The y axis is clear and may not need naming. Besides that, the analysis looks great!

Thanks Taylore. I've added better legends.

**Comment by captainbrosset** [comment]
@tidoust mind giving this a look and letting us know if you have any comments?

**Comment by tidoust** [comment]
Interpretation looks good to me.

For past surveys, we also published raw results in a CSV file, so that people can compute their own statistics and interpretation. Would it be possible to do the same here?

Also, could you add an entry to the table in the [README](https://github.com/web-platform-dx/developer-research/tree/main?tab=readme-ov-file#history-of-surveys-tracked-by-the-group)? (Side note: it occurs to me that this table is incomplete, it should also list the latest State of survey results).

**Comment by tidoust** [comment]
Ah, the raw data I was thinking about is really the raw data, not agglomerated numbers. That's what we did for past surveys, such as [the one on security](https://github.com/web-platform-dx/developer-research/blob/main/mdn-short-surveys/2023-05-15-security-dx/results.csv). The raw data is needed to relate Q1, Q2 and Q3 answers (you do some of that in the interpretation, it cannot be done with agglomerated numbers).

Free-form text is not a problem per se provided it gets pruned of personally identifiable information. If you look at security survey results, you'll see instances of `[noise redacted - xx]` and `[PII redacted - xx]` (with `xx` incremented for each comment) in the last column.

**Comment by captainbrosset** [comment]
Unfortunately I don't have this data. Maybe @rumyra does.

**Review by tidoust — APPROVED** [review]

**Pull request merged**
